from flask import Blueprint, request, jsonify
from flask_login import current_user
from app import csrf
from app.extensions import db
from app.models import Job, AiChatMessage, get_formatted_12hr_time
from app.ai_service import generate_chat_response
from app.resume_analyzer import (
    extract_text_from_file,
    validate_resume_structure,
    calculate_resume_job_match
)

ai_bp = Blueprint('ai', __name__)

MANDATORY_DISCLAIMER = "Disclaimer: This analysis is generated by an automated AI tool to help you evaluate skill alignment. It does not guarantee interview shortlisting or employment."


@ai_bp.route('/api/ai/chat', methods=['POST'])
@csrf.exempt
def chat():
    """
    Primary API Endpoint for Candidate AI Floating Assistant.
    """
    try:
        data = request.get_json(silent=True) or {}
        messages = data.get('messages', [])

        if not messages:
            return jsonify({
                "success": False,
                "error": "No message content provided in request."
            }), 400

        role = 'candidate'
        user_obj = None

        if current_user.is_authenticated:
            user_obj = current_user
            if current_user.is_employer():
                return jsonify({
                    "success": False,
                    "error": "AI Chatbot is disabled for employer accounts."
                }), 403
            elif current_user.is_candidate():
                role = 'candidate'

        result = generate_chat_response(messages=messages, role=role, user=user_obj)

        # Save Chat Record to Supabase Database with 12-hr local time
        try:
            last_prompt = messages[-1].get('content', '') if messages else ''
            fmt_time = get_formatted_12hr_time()
            chat_rec = AiChatMessage(
                user_id=current_user.id if current_user.is_authenticated else None,
                job_id=None,
                sender_role='user',
                prompt_text=last_prompt,
                reply_text=result.get('reply', ''),
                formatted_time=fmt_time
            )
            db.session.add(chat_rec)
            db.session.commit()
        except Exception:
            db.session.rollback()

        return jsonify(result)

    except Exception as e:
        return jsonify({
            "success": False,
            "error": f"Internal chatbot routing error: {str(e)}",
            "reply": "⚠️ An internal error occurred while connecting to the AI Assistant. Please refresh and try again."
        }), 500


@ai_bp.route('/api/v1/analyze-resume', methods=['POST'])
@csrf.exempt
def analyze_resume_endpoint():
    """
    API Endpoint: POST /api/v1/analyze-resume
    Payload: Multipart FormData containing 'job_id' and 'resume_file'
    Extracts text, performs authenticity/fake-doc check, calculates weighted match score,
    and returns JSON with initial evaluation markdown summary.
    """
    try:
        job_id = request.form.get('job_id')
        if not job_id:
            return jsonify({
                "success": False,
                "error": "Job ID is required for resume analysis."
            }), 400

        job = Job.query.get(int(job_id))
        if not job:
            return jsonify({
                "success": False,
                "error": "Target job posting not found."
            }), 444

        if 'resume_file' not in request.files:
            return jsonify({
                "success": False,
                "error": "Please upload a resume file (PDF, PNG, JPG, JPEG)."
            }), 400

        file_storage = request.files['resume_file']
        if not file_storage or not file_storage.filename:
            return jsonify({
                "success": False,
                "error": "Invalid or empty file uploaded."
            }), 400

        # 1. Document Text Extraction
        extracted_text, extract_err = extract_text_from_file(file_storage)
        if extract_err:
            return jsonify({
                "success": False,
                "error": extract_err
            }), 400

        # 2. Strict Authenticity & Fake-Document Filter
        is_valid, validation_msg = validate_resume_structure(extracted_text)
        if not is_valid:
            return jsonify({
                "success": False,
                "is_valid_resume": False,
                "error": validation_msg
            }), 422

        # 3. Analytics Engine & Match Percentage Calculation
        match_data = calculate_resume_job_match(extracted_text, job)

        # 4. Construct AI System Prompt for Initial Structured Card
        matched_str = ", ".join(match_data["matched_skills"]) if match_data["matched_skills"] else "None explicitly matching"
        missing_str = ", ".join(match_data["missing_skills"]) if match_data["missing_skills"] else "None identified (Great alignment!)"
        cand_all_skills_str = ", ".join(match_data.get("candidate_all_skills", [])[:12]) if match_data.get("candidate_all_skills") else "General background"
        is_low_match = match_data['match_percentage'] < 25 or len(match_data['matched_skills']) == 0

        non_resume_warning = ""
        if is_low_match or not match_data.get('ats_checklist', {}).get('skills_section'):
            non_resume_warning = (
                "> ⚠️ **CRITICAL ATS NOTICE: It seems like the uploaded file is not a resume or CV.**\n"
                "> *This document lacks an explicit 'Skills' or 'Technical Stack' section and has no keyword alignment with this role. "
                "If this is your resume, ensure you include recognized headings such as **Skills**, **Work Experience**, and **Education** "
                "so enterprise ATS screeners do not automatically reject your application.*\n\n"
            )

        prompt_system = f"""
You are an expert Enterprise ATS (Applicant Tracking System) Screener and Principal Technical Recruiter evaluating a candidate's resume for the role of "{job.title}".

Job Context & Requirements:
- Title: {job.title}
- Company: {job.company.name if job.company else 'Hiring Employer'}
- Core Required Skills: {", ".join(match_data["combined_job_skills"])}
- Job Description / Requirements: {job.description[:1200] if job.description else ''}

ATS Evaluation Metrics:
- Calculated ATS Match Score: {match_data['match_percentage']}% ({match_data['badge_label']})
- Matched Job Skills: {matched_str}
- Missing Key Keywords: {missing_str}
- Candidate Extracted Skills: {cand_all_skills_str}
- ATS Structural Health: {match_data.get('ats_health_pct', 80)}%
- Is Low / Non-Resume Document: {is_low_match}

Generate a comprehensive, ultra-detailed ATS-grade feedback report formatted in clean Markdown:

{non_resume_warning if is_low_match else ""}### 🎯 ATS Compatibility & Screener Overview
- **Match Score**: **{match_data['match_percentage']}%** ({match_data['badge_label']})
- **ATS Parseability Health**: **{match_data.get('ats_health_pct', 80)}%**
- **ATS Screener Verdict**: {"⚠️ Document appears not to be a standard resume or lacks required technical skills." if is_low_match else "✅ Document parsed successfully by ATS screener."}

### 🟢 Matched Core Competencies
(Bulleted list of skills in the resume matching "{job.title}". If none, clearly explain that no matching skills were found.)

### 🔴 Missing Critical Keywords & Skill Gaps
(Bulleted list of high-priority job keywords missing from candidate's resume that recruiter filters require)

### 📋 ATS Health & Formatting Check
- Contact & Header Information: {"✅ Detected" if match_data.get('ats_checklist', {}).get('contact_info') else "⚠️ Missing contact details"}
- Skills Section Structure: {"✅ Clear & Parseable" if match_data.get('ats_checklist', {}).get('skills_section') else "⚠️ Needs explicit 'Skills' heading"}
- Work Experience History: {"✅ Formatted" if match_data.get('ats_checklist', {}).get('experience_section') else "⚠️ Unstructured experience"}
- Bullet Points & Clarity: {"✅ Machine-readable" if match_data.get('ats_checklist', {}).get('bullet_points') else "⚠️ Use clean bullet points"}

### 💡 Step-by-Step Optimization Tips
1. Exact keywords to integrate for "{job.title}".
2. How to showcase impact with metrics (e.g., % improvement, scale).
3. Tailoring your professional headline and summary for {job.company.name if job.company else 'this employer'}.

Formatting Rules:
- Use clean standard markdown (### for main sections, #### for subheadings, - for bullets, numbers for steps).
- Do NOT output broken tags like '* ###' or '* **'.
"""
        # Call LLM to format response
        messages_llm = [
            {"role": "user", "content": prompt_system}
        ]
        ai_res = generate_chat_response(
            messages=messages_llm,
            role="candidate",
            user=current_user if current_user.is_authenticated else None,
            custom_system_prompt=prompt_system,
            job_obj=job,
            resume_text=extracted_text
        )
        initial_markdown = ai_res.get('reply', '')

        if not initial_markdown:
            initial_markdown = f"""{non_resume_warning}### 🎯 ATS Compatibility & Screener Overview
- **Match Score**: **{match_data['match_percentage']}%** ({match_data['badge_label']})
- **ATS Parseability Health**: **{match_data.get('ats_health_pct', 80)}%**
- **ATS Screener Verdict**: {"⚠️ Document appears not to be a standard resume or lacks required technical skills." if is_low_match else "✅ Document parsed successfully by ATS screener."}

### 🟢 Matched Core Competencies
{chr(10).join(['- ' + s for s in match_data['matched_skills']]) if match_data['matched_skills'] else '- None explicitly matching the required data stack. The current resume lacks direct keyword alignment.'}

### 🔴 Missing Critical Keywords & Skill Gaps
{chr(10).join(['- ' + s for s in match_data['missing_skills']]) if match_data['missing_skills'] else '- No critical skill gaps found for this posting!'}

### 📋 ATS Health & Formatting Check
- **Contact Details**: {"✅ Detected" if match_data.get('ats_checklist', {}).get('contact_info') else "⚠️ Missing contact details"}
- **Skills Section**: {"✅ Clear & Parseable" if match_data.get('ats_checklist', {}).get('skills_section') else "⚠️ Needs explicit 'Skills' heading"}
- **Work History**: {"✅ Formatted" if match_data.get('ats_checklist', {}).get('experience_section') else "⚠️ Needs clear 'Experience' section"}
- **Action Verbs**: {"✅ Good structure" if match_data.get('ats_checklist', {}).get('bullet_points') else "⚠️ Use bullet points"}

### 💡 Step-by-Step Optimization Tips
1. **Keyword Optimization**: Integrate missing keywords like `{missing_str}` into a dedicated Skills section.
2. **Quantify Impact**: Include numbers and measurable achievements (e.g. "Increased performance by 30%").
3. **Role Alignment**: Tailor your headline and summary to explicitly match `{job.title}`.
"""

        # Save Initial Resume Analysis Record to Supabase Database
        try:
            fmt_time = get_formatted_12hr_time()
            chat_rec = AiChatMessage(
                user_id=current_user.id if current_user.is_authenticated else None,
                job_id=job.id,
                sender_role='assistant',
                prompt_text=f"Uploaded Resume for Analysis: {file_storage.filename}",
                reply_text=initial_markdown,
                match_score=match_data["match_percentage"],
                formatted_time=fmt_time
            )
            db.session.add(chat_rec)
            db.session.commit()
        except Exception:
            db.session.rollback()

        return jsonify({
            "success": True,
            "is_valid_resume": True,
            "job_id": job.id,
            "job_title": job.title,
            "match_percentage": match_data["match_percentage"],
            "badge_color": match_data["badge_color"],
            "badge_label": match_data["badge_label"],
            "matched_skills": match_data["matched_skills"],
            "missing_skills": match_data["missing_skills"],
            "analysis_markdown": initial_markdown,
            "resume_text_snippet": extracted_text[:3000],
            "disclaimer": MANDATORY_DISCLAIMER
        })

    except Exception as e:
        return jsonify({
            "success": False,
            "error": f"Error during resume analysis: {str(e)}"
        }), 500


@ai_bp.route('/api/v1/chat-resume', methods=['POST'])
@csrf.exempt
def chat_resume_endpoint():
    """
    API Endpoint: POST /api/v1/chat-resume
    Payload: JSON containing 'job_id', 'resume_text', 'prompt', 'messages'
    Handles follow-up conversation turns retaining active job description + candidate resume context.
    """
    try:
        data = request.get_json(silent=True) or {}
        job_id = data.get('job_id')
        resume_text = data.get('resume_text', '')
        user_prompt = data.get('prompt', '')
        history = data.get('messages', [])

        if not job_id:
            return jsonify({
                "success": False,
                "error": "Job ID is required."
            }), 400

        job = Job.query.get(int(job_id))
        if not job:
            return jsonify({
                "success": False,
                "error": "Job not found."
            }), 404

        if not user_prompt and not history:
            return jsonify({
                "success": False,
                "error": "Prompt or message history required."
            }), 400

        match_data = calculate_resume_job_match(resume_text, job)
        comp_name = job.company.name if (job.company and job.company.name) else 'Analysis Workforce'

        from app.ai_service import extract_candidate_credentials
        profile_dict = {}
        if current_user.is_authenticated and hasattr(current_user, 'id'):
            from app.models import Candidate
            cand_obj = Candidate.query.filter_by(user_id=current_user.id).first()
            if cand_obj:
                profile_dict = {
                    'full_name': cand_obj.full_name,
                    'email': current_user.email,
                    'phone': cand_obj.phone,
                    'github_url': cand_obj.github_url,
                    'linkedin_url': cand_obj.linkedin_url
                }

        creds = extract_candidate_credentials(current_user if current_user.is_authenticated else None, profile_dict, resume_text)

        # Construct System Context & Persona Instructions
        context_prompt = f"""
You are an elite Senior Technical Recruiter and HR Advisor for CareerPearls.
You are helping a candidate evaluate and optimize their resume specifically for the job: "{job.title}" at {comp_name}.

Candidate Real Credentials:
- Name: {creds['name']}
- Email: {creds['email']}
- Phone: {creds['phone']}
- GitHub: {creds['github']}
- Date: {creds['date']}

Target Job Details:
- Job Title: {job.title}
- Company: {comp_name}
- Required Job Skills: {', '.join(match_data['combined_job_skills'])}
- Job Description & Requirements:
{job.description}

Calculated Weighted Match Score: {match_data['match_percentage']}% ({match_data['badge_label']})
Matched Skills Identified for THIS Job: {', '.join(match_data['matched_skills']) if match_data['matched_skills'] else 'General domain alignment'}
Missing Required Skills for THIS Job ONLY: {', '.join(match_data['missing_skills']) if match_data['missing_skills'] else 'None identified'}

Candidate's Extracted Resume Content:
{resume_text[:4000]}

STRICT POLICY & GUIDELINES FOR RESPONSES:
1. Ready-Made Cover Letter Generation:
   - When asked to draft a cover letter or application letter for this position, ALWAYS generate a complete, formal, ready-made cover letter.
   - NEVER use generic placeholders like [Your Name], [Contact Info], [Date], or [Company Name].
   - ALWAYS use the real candidate credentials provided above: Name (**{creds['name']}**), Email (*{creds['email']}*), Phone (*{creds['phone']}*), GitHub (*{creds['github']}*), Date (*{creds['date']}*).
   - Format with bold (**Name**) and italic (*Contact*) text styling.
   - The opening body paragraph MUST start with:
     "Hi, I am **{creds['name']}**. I am writing to express my strong enthusiasm and interest in applying for the **{job.title}** position at **{comp_name}**."
   - Tailor all paragraphs using the matched required skills ({', '.join(match_data['matched_skills'])}).

2. High-Accuracy Skill Gap Analysis:
   - Provide a deep, accurate breakdown of matched vs missing skills ONLY for THIS job ({job.title}).
   - List strengths for matched skills and clear recommendations for missing skills ({', '.join(match_data['missing_skills'])}).
   - NEVER suggest unrelated platform skills like TensorFlow or Design Systems unless explicitly in THIS job's requirements.

3. High-Impact Match Score Improvement:
   - Provide a 4-step actionable strategy (Summary rewrite, quantified experience bullets, portfolio links, keyword alignment) to elevate the match score to 95%+.
"""

        # Format conversation messages for LLM
        formatted_messages = [{"role": "system", "content": context_prompt}]
        for m in history:
            if m.get('content'):
                formatted_messages.append({
                    "role": m.get('role', 'user'),
                    "content": m.get('content')
                })

        if user_prompt and (not history or history[-1].get('content') != user_prompt):
            formatted_messages.append({"role": "user", "content": user_prompt})

        result = generate_chat_response(
            messages=formatted_messages,
            role="candidate",
            user=current_user if current_user.is_authenticated else None,
            custom_system_prompt=context_prompt,
            job_obj=job,
            resume_text=resume_text
        )

        # Save Chat Record to Supabase Database with 12-hr local time
        try:
            fmt_time = get_formatted_12hr_time()
            chat_rec = AiChatMessage(
                user_id=current_user.id if current_user.is_authenticated else None,
                job_id=job.id,
                sender_role='user',
                prompt_text=user_prompt,
                reply_text=result.get('reply', ''),
                formatted_time=fmt_time
            )
            db.session.add(chat_rec)
            db.session.commit()
        except Exception:
            db.session.rollback()

        return jsonify({
            "success": True,
            "reply": result.get('reply', ''),
            "formatted_time": fmt_time
        })

    except Exception as e:
        return jsonify({
            "success": False,
            "error": f"Error processing resume chat query: {str(e)}"
        }), 500


@ai_bp.route('/api/v1/resume-chat-history', methods=['GET'])
@csrf.exempt
def resume_chat_history_endpoint():
    """
    API Endpoint: GET /api/v1/resume-chat-history?job_id=<job_id>
    Fetches stored AI Resume analysis and conversation history for the current candidate and job.
    Ensures chats persist across page refreshes and hard refreshes until explicitly deleted.
    """
    try:
        job_id = request.args.get('job_id')
        if not job_id:
            return jsonify({
                "success": False,
                "error": "Job ID parameter is required."
            }), 400

        job = Job.query.get(int(job_id))
        if not job:
            return jsonify({
                "success": False,
                "error": "Target job posting not found."
            }), 404

        query = AiChatMessage.query.filter_by(job_id=job.id)
        if current_user.is_authenticated:
            query = query.filter_by(user_id=current_user.id)
        else:
            query = query.filter_by(user_id=None)

        records = query.order_by(AiChatMessage.created_at.asc()).all()
        if not records:
            return jsonify({
                "success": True,
                "has_history": False,
                "job_id": job.id,
                "messages": []
            })

        # Identify initial analysis vs follow-up messages
        initial_record = None
        for rec in records:
            if rec.prompt_text and (rec.prompt_text.startswith("Uploaded Resume for Analysis:") or rec.match_score is not None):
                initial_record = rec
                break

        messages_list = []
        for rec in records:
            if rec == initial_record:
                continue
            if rec.prompt_text:
                messages_list.append({
                    "role": "user",
                    "content": rec.prompt_text,
                    "formatted_time": rec.formatted_time
                })
            if rec.reply_text:
                messages_list.append({
                    "role": "assistant",
                    "content": rec.reply_text,
                    "formatted_time": rec.formatted_time
                })

        initial_data = None
        if initial_record:
            score = initial_record.match_score if initial_record.match_score is not None else 50
            if score >= 75:
                badge_color = 'green'
                badge_label = 'High ATS Match / Top Tier Candidate'
            elif score >= 45:
                badge_color = 'orange'
                badge_label = 'Moderate Match / Key Skill Gaps'
            else:
                badge_color = 'red'
                badge_label = 'Low ATS Match / High Rejection Risk'

            initial_data = {
                "match_percentage": score,
                "badge_color": badge_color,
                "badge_label": badge_label,
                "analysis_markdown": initial_record.reply_text or "",
                "formatted_time": initial_record.formatted_time,
                "disclaimer": MANDATORY_DISCLAIMER
            }

        return jsonify({
            "success": True,
            "has_history": True,
            "job_id": job.id,
            "initial_analysis": initial_data,
            "messages": messages_list
        })

    except Exception as e:
        return jsonify({
            "success": False,
            "error": f"Error fetching resume chat history: {str(e)}"
        }), 500


@ai_bp.route('/api/v1/delete-resume-chat', methods=['POST'])
@csrf.exempt
def delete_resume_chat_endpoint():
    """
    API Endpoint: POST /api/v1/delete-resume-chat
    Payload: JSON with 'job_id'
    Explicitly removes all resume analysis & chat history records for this job/candidate.
    """
    try:
        data = request.get_json(silent=True) or {}
        job_id = data.get('job_id')
        if not job_id:
            return jsonify({
                "success": False,
                "error": "Job ID is required to clear history."
            }), 400

        query = AiChatMessage.query.filter_by(job_id=int(job_id))
        if current_user.is_authenticated:
            query = query.filter_by(user_id=current_user.id)
        else:
            query = query.filter_by(user_id=None)

        deleted_count = query.delete(synchronize_session=False)
        db.session.commit()

        return jsonify({
            "success": True,
            "deleted_count": deleted_count,
            "message": "Resume chat history successfully deleted."
        })

    except Exception as e:
        db.session.rollback()
        return jsonify({
            "success": False,
            "error": f"Error clearing resume chat history: {str(e)}"
        }), 500

