from flask import Blueprint, request, jsonify
from flask_login import current_user
from app import csrf
from app.extensions import db
from app.models import Job, AiChatMessage, get_formatted_12hr_time
from app.ai_service import generate_chat_response
from app.resume_analyzer import (
    extract_text_from_file,
    validate_resume_structure,
    calculate_resume_job_match
)

ai_bp = Blueprint('ai', __name__)

MANDATORY_DISCLAIMER = "Disclaimer: This analysis is generated by an automated AI tool to help you evaluate skill alignment. It does not guarantee interview shortlisting or employment."


@ai_bp.route('/api/ai/chat', methods=['POST'])
@csrf.exempt
def chat():
    """
    Primary API Endpoint for Candidate AI Floating Assistant.
    """
    try:
        data = request.get_json(silent=True) or {}
        messages = data.get('messages', [])

        if not messages:
            return jsonify({
                "success": False,
                "error": "No message content provided in request."
            }), 400

        role = 'candidate'
        user_obj = None

        if current_user.is_authenticated:
            user_obj = current_user
            if current_user.is_employer():
                return jsonify({
                    "success": False,
                    "error": "AI Chatbot is disabled for employer accounts."
                }), 403
            elif current_user.is_candidate():
                role = 'candidate'

        result = generate_chat_response(messages=messages, role=role, user=user_obj)

        # Save Chat Record to Supabase Database with 12-hr local time
        try:
            last_prompt = messages[-1].get('content', '') if messages else ''
            fmt_time = get_formatted_12hr_time()
            chat_rec = AiChatMessage(
                user_id=current_user.id if current_user.is_authenticated else None,
                job_id=None,
                sender_role='user',
                prompt_text=last_prompt,
                reply_text=result.get('reply', ''),
                formatted_time=fmt_time
            )
            db.session.add(chat_rec)
            db.session.commit()
        except Exception:
            db.session.rollback()

        return jsonify(result)

    except Exception as e:
        return jsonify({
            "success": False,
            "error": f"Internal chatbot routing error: {str(e)}",
            "reply": "⚠️ An internal error occurred while connecting to the AI Assistant. Please refresh and try again."
        }), 500


@ai_bp.route('/api/v1/analyze-resume', methods=['POST'])
@csrf.exempt
def analyze_resume_endpoint():
    """
    API Endpoint: POST /api/v1/analyze-resume
    Payload: Multipart FormData containing 'job_id' and 'resume_file'
    Extracts text, performs authenticity/fake-doc check, calculates weighted match score,
    and returns JSON with initial evaluation markdown summary.
    """
    try:
        job_id = request.form.get('job_id')
        if not job_id:
            return jsonify({
                "success": False,
                "error": "Job ID is required for resume analysis."
            }), 400

        job = Job.query.get(int(job_id))
        if not job:
            return jsonify({
                "success": False,
                "error": "Target job posting not found."
            }), 444

        if 'resume_file' not in request.files:
            return jsonify({
                "success": False,
                "error": "Please upload a resume file (PDF, PNG, JPG, JPEG)."
            }), 400

        file_storage = request.files['resume_file']
        if not file_storage or not file_storage.filename:
            return jsonify({
                "success": False,
                "error": "Invalid or empty file uploaded."
            }), 400

        # 1. Document Text Extraction
        extracted_text, extract_err = extract_text_from_file(file_storage)
        if extract_err:
            return jsonify({
                "success": False,
                "error": extract_err
            }), 400

        # 2. Strict Authenticity & Fake-Document Filter
        is_valid, validation_msg = validate_resume_structure(extracted_text)
        if not is_valid:
            return jsonify({
                "success": False,
                "is_valid_resume": False,
                "error": validation_msg
            }), 422

        # 3. Analytics Engine & Match Percentage Calculation
        match_data = calculate_resume_job_match(extracted_text, job)

        # 4. Construct AI System Prompt for Initial Structured Card
        matched_str = ", ".join(match_data["matched_skills"]) if match_data["matched_skills"] else "General domain skills"
        missing_str = ", ".join(match_data["missing_skills"]) if match_data["missing_skills"] else "None identified"

        prompt_system = f"""
You are an elite Senior Technical Recruiter and HR Analytics Specialist evaluating a candidate's resume for the role of "{job.title}".

Job Description & Requirements:
{job.description}

Calculated Weighted Match Score: {match_data['match_percentage']}% ({match_data['badge_label']})
Matched Skills Identified: {matched_str}
Missing Key Skills: {missing_str}

Please generate an initial candidate feedback response formatted cleanly in Markdown:

1. **Match Overview**: State the score {match_data['match_percentage']}% with badge label "{match_data['badge_label']}".
2. **Matched Skills**: Bulleted list of candidate strengths matching this job.
3. **Missing / Gap Skills**: Bulleted list of key job requirements missing or weak in the resume.
4. **Actionable Recommendations**: 2-3 specific, high-impact suggestions to tailor the resume for this position.
Formatting Instruction:
- Do NOT combine bullet points with heading tags (NEVER output '* ###' or '* **'). Use clean Markdown headings (### Heading) and clean bullet lists (- Item).
- Use clear bold text (**Key Concept**) and distinct section titles.
"""
        # Call LLM to format response
        messages_llm = [
            {"role": "user", "content": prompt_system}
        ]
        ai_res = generate_chat_response(
            messages=messages_llm,
            role="candidate",
            user=current_user if current_user.is_authenticated else None,
            custom_system_prompt=prompt_system,
            job_obj=job,
            resume_text=extracted_text
        )
        initial_markdown = ai_res.get('reply', '')

        if not initial_markdown:
            initial_markdown = f"""### 📊 Resume Analysis Summary

- **Match Score**: **{match_data['match_percentage']}%** ({match_data['badge_label']})

#### ✅ Matched Skills
{chr(10).join(['- ' + s for s in match_data['matched_skills']]) if match_data['matched_skills'] else '- Domain background alignment'}

#### ⚠️ Skill Gaps & Missing Requirements
{chr(10).join(['- ' + s for s in match_data['missing_skills']]) if match_data['missing_skills'] else '- No critical skill gaps found!'}

#### 💡 Actionable Recommendations
1. Highlight relevant project accomplishments related to {job.title}.
2. Quantify achievements with metrics (e.g. reduced load times, increased conversion).
3. Tailor your summary section specifically to target {job.company.name if job.company else 'the employer'}'s core requirements.

> *{MANDATORY_DISCLAIMER}*
"""

        # Save Initial Resume Analysis Record to Supabase Database
        try:
            fmt_time = get_formatted_12hr_time()
            chat_rec = AiChatMessage(
                user_id=current_user.id if current_user.is_authenticated else None,
                job_id=job.id,
                sender_role='assistant',
                prompt_text=f"Uploaded Resume for Analysis: {file_storage.filename}",
                reply_text=initial_markdown,
                match_score=match_data["match_percentage"],
                formatted_time=fmt_time
            )
            db.session.add(chat_rec)
            db.session.commit()
        except Exception:
            db.session.rollback()

        return jsonify({
            "success": True,
            "is_valid_resume": True,
            "job_id": job.id,
            "job_title": job.title,
            "match_percentage": match_data["match_percentage"],
            "badge_color": match_data["badge_color"],
            "badge_label": match_data["badge_label"],
            "matched_skills": match_data["matched_skills"],
            "missing_skills": match_data["missing_skills"],
            "analysis_markdown": initial_markdown,
            "resume_text_snippet": extracted_text[:3000],
            "disclaimer": MANDATORY_DISCLAIMER
        })

    except Exception as e:
        return jsonify({
            "success": False,
            "error": f"Error during resume analysis: {str(e)}"
        }), 500


@ai_bp.route('/api/v1/chat-resume', methods=['POST'])
@csrf.exempt
def chat_resume_endpoint():
    """
    API Endpoint: POST /api/v1/chat-resume
    Payload: JSON containing 'job_id', 'resume_text', 'prompt', 'messages'
    Handles follow-up conversation turns retaining active job description + candidate resume context.
    """
    try:
        data = request.get_json(silent=True) or {}
        job_id = data.get('job_id')
        resume_text = data.get('resume_text', '')
        user_prompt = data.get('prompt', '')
        history = data.get('messages', [])

        if not job_id:
            return jsonify({
                "success": False,
                "error": "Job ID is required."
            }), 400

        job = Job.query.get(int(job_id))
        if not job:
            return jsonify({
                "success": False,
                "error": "Job not found."
            }), 404

        if not user_prompt and not history:
            return jsonify({
                "success": False,
                "error": "Prompt or message history required."
            }), 400

        match_data = calculate_resume_job_match(resume_text, job)
        comp_name = job.company.name if (job.company and job.company.name) else 'Analysis Workforce'

        from app.ai_service import extract_candidate_credentials
        profile_dict = {}
        if current_user.is_authenticated and hasattr(current_user, 'id'):
            from app.models import Candidate
            cand_obj = Candidate.query.filter_by(user_id=current_user.id).first()
            if cand_obj:
                profile_dict = {
                    'full_name': cand_obj.full_name,
                    'email': current_user.email,
                    'phone': cand_obj.phone,
                    'github_url': cand_obj.github_url,
                    'linkedin_url': cand_obj.linkedin_url
                }

        creds = extract_candidate_credentials(current_user if current_user.is_authenticated else None, profile_dict, resume_text)

        # Construct System Context & Persona Instructions
        context_prompt = f"""
You are an elite Senior Technical Recruiter and HR Advisor for CareerPearls.
You are helping a candidate evaluate and optimize their resume specifically for the job: "{job.title}" at {comp_name}.

Candidate Real Credentials:
- Name: {creds['name']}
- Email: {creds['email']}
- Phone: {creds['phone']}
- GitHub: {creds['github']}
- Date: {creds['date']}

Target Job Details:
- Job Title: {job.title}
- Company: {comp_name}
- Required Job Skills: {', '.join(match_data['combined_job_skills'])}
- Job Description & Requirements:
{job.description}

Calculated Weighted Match Score: {match_data['match_percentage']}% ({match_data['badge_label']})
Matched Skills Identified for THIS Job: {', '.join(match_data['matched_skills']) if match_data['matched_skills'] else 'General domain alignment'}
Missing Required Skills for THIS Job ONLY: {', '.join(match_data['missing_skills']) if match_data['missing_skills'] else 'None identified'}

Candidate's Extracted Resume Content:
{resume_text[:4000]}

STRICT POLICY & GUIDELINES FOR RESPONSES:
1. Ready-Made Cover Letter Generation:
   - When asked to draft a cover letter or application letter for this position, ALWAYS generate a complete, formal, ready-made cover letter.
   - NEVER use generic placeholders like [Your Name], [Contact Info], [Date], or [Company Name].
   - ALWAYS use the real candidate credentials provided above: Name (**{creds['name']}**), Email (*{creds['email']}*), Phone (*{creds['phone']}*), GitHub (*{creds['github']}*), Date (*{creds['date']}*).
   - Format with bold (**Name**) and italic (*Contact*) text styling.
   - The opening body paragraph MUST start with:
     "Hi, I am **{creds['name']}**. I am writing to express my strong enthusiasm and interest in applying for the **{job.title}** position at **{comp_name}**."
   - Tailor all paragraphs using the matched required skills ({', '.join(match_data['matched_skills'])}).

2. High-Accuracy Skill Gap Analysis:
   - Provide a deep, accurate breakdown of matched vs missing skills ONLY for THIS job ({job.title}).
   - List strengths for matched skills and clear recommendations for missing skills ({', '.join(match_data['missing_skills'])}).
   - NEVER suggest unrelated platform skills like TensorFlow or Design Systems unless explicitly in THIS job's requirements.

3. High-Impact Match Score Improvement:
   - Provide a 4-step actionable strategy (Summary rewrite, quantified experience bullets, portfolio links, keyword alignment) to elevate the match score to 95%+.
"""

        # Format conversation messages for LLM
        formatted_messages = [{"role": "system", "content": context_prompt}]
        for m in history:
            if m.get('content'):
                formatted_messages.append({
                    "role": m.get('role', 'user'),
                    "content": m.get('content')
                })

        if user_prompt and (not history or history[-1].get('content') != user_prompt):
            formatted_messages.append({"role": "user", "content": user_prompt})

        result = generate_chat_response(
            messages=formatted_messages,
            role="candidate",
            user=current_user if current_user.is_authenticated else None,
            custom_system_prompt=context_prompt,
            job_obj=job,
            resume_text=resume_text
        )

        # Save Chat Record to Supabase Database with 12-hr local time
        try:
            fmt_time = get_formatted_12hr_time()
            chat_rec = AiChatMessage(
                user_id=current_user.id if current_user.is_authenticated else None,
                job_id=job.id,
                sender_role='user',
                prompt_text=user_prompt,
                reply_text=result.get('reply', ''),
                formatted_time=fmt_time
            )
            db.session.add(chat_rec)
            db.session.commit()
        except Exception:
            db.session.rollback()

        return jsonify({
            "success": True,
            "reply": result.get('reply', ''),
            "formatted_time": fmt_time
        })

    except Exception as e:
        return jsonify({
            "success": False,
            "error": f"Error processing resume chat query: {str(e)}"
        }), 500
